class Utils {
  final Map<String, String> japaneseTitles = {
    'id': 'ID',
    'name': '名前',
    'store': '購入店',
    'imagePath': '画像パス',
    'purchaseDate': '購入日',
    'updateDate': '更新日',
    'price': '価格',
    'purchasedGrams': '購入グラム数',
    'origin': '産地',
    'farmName': '農園名',
    'variety': '品種',
    'roastLevel': '焙煎度',
    'body': 'ボディ',
    'acidity': '酸味',
    'story': 'ストーリー',
    'usedBeans': '使用した豆',
    'deviceUsed': '使用器具',
    'brewDate': '抽出日',
    'overallScore': '総合点数',
    'overallMemo': '総合メモ',
    'acidityScore': '酸味',
    'acidityMemo': '酸味に関するメモ',
    'aromaScore': '香り',
    'aromaMemo': '香りに関するメモ',
    'bitternessScore': '苦味',
    'bitternessMemo': '苦味に関するメモ',
    'bodyScore': 'ボディ',
    'bodyMemo': 'ボディに関するメモ',
    'sweetnessScore': '甘味',
    'sweetnessMemo': '甘味に関するメモ',
  };
}
